### ISSUE TITLE
[Bug]: it doesn't work

### ISSUE THREAD

**Issue by mescalito** [sabertazimi/bod#702]
after running:
npx bod create bod
and then: 
npm run
I get this error:

![image](https://user-images.githubusercontent.com/687283/164042301-370d7ea9-590b-44cd-ae8e-d6a9027be21e.png)

## **Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by sabertazimi** [comment]
Solution:

1. Change `createRoot` to legacy `ReactDOM.render`.
2. Re-create app with bod@5.9.0:

```bash
npx bod@latest create bod
```

**Comment by sabertazimi** [comment]
If it can help, you can close this issue feel free.

**Comment by mescalito** [comment]
Hi @sabertazimi 
I just wanted to let you know that the command "npx bod create bod" stated on the npm page (https://www.npmjs.com/package/cra-template-bod) is not working and the solution you have been working on for so long is not working out of the box.
Yes, I can fix the issue, but my question to you is: why deliver something that doesn't work out of the box?
I hope my point makes sense.
Thanks!

**Comment by sabertazimi** [comment]
When I released `@sabertazimi/cra-template-typescript` v5.8.1, [@types/react-dom v17.0.14](https://unpkg.com/browse/@types/react-dom@17.0.14/) contains `client.d.ts`.
So it passed [E2E testing on GitHub CI](https://github.com/sabertazimi/bod/actions/runs/2085014706).

But after that, [@types/react-dom v17.0.15](https://unpkg.com/browse/@types/react-dom@17.0.15/) removed `client.d.ts` (I don't know why React team puts breaking change in patch version).
As a result, [E2E testing on GitHub CI](https://github.com/sabertazimi/bod/actions/runs/2140146685) failed.

Then I fixed it by updating `@types/react-dom` to v18, but I forgot release this change to npm.
After you find this issue, I released `@sabertazimi/cra-template-typescript` v5.9.0 to npm.
