### ISSUE TITLE
A '/bod/bod/' is leading in the url

### ISSUE THREAD

**Issue by onaret** [sabertazimi/bod#720]
Hello Sabertaz,

For some reason, there is a leading '/bod/bod/' in the URL of all my routes such as `host:/bod/bod/whatever`
I cannot find a place in the configuration where it is defined
Is it me who is missing the obvious or is this an issue?

Anyway, thank you for the great work.
Olivier

**Comment by sabertazimi** [comment]
Just change `homepage` in `package.json`.

See more details [here](https://create-react-app.dev/docs/deployment#building-for-relative-paths).
